package prueba.modelo;
// Generated 10-11-2017 6:27:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Date fechaInicio;
     private String estado;
     private int presupuestoInicial;
     private int presupuestoGastado;
     private int comunaId;

    public Proyecto() {
    }

    public Proyecto(String nombre, String descripcion, Date fechaInicio, String estado, int presupuestoInicial, int presupuestoGastado, int comunaId) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.estado = estado;
       this.presupuestoInicial = presupuestoInicial;
       this.presupuestoGastado = presupuestoGastado;
       this.comunaId = comunaId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getPresupuestoInicial() {
        return this.presupuestoInicial;
    }
    
    public void setPresupuestoInicial(int presupuestoInicial) {
        this.presupuestoInicial = presupuestoInicial;
    }
    public int getPresupuestoGastado() {
        return this.presupuestoGastado;
    }
    
    public void setPresupuestoGastado(int presupuestoGastado) {
        this.presupuestoGastado = presupuestoGastado;
    }
    public int getComunaId() {
        return this.comunaId;
    }
    
    public void setComunaId(int comunaId) {
        this.comunaId = comunaId;
    }




}


